stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - echo "Кузов" >> car_details.txt
    - echo "Двигун" >> car_details.txt
    - echo "Колеса" >> car_details.txt
    - echo "Сидіння" >> car_details.txt
    - echo "Кермо" >> car_details.txt
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - cd build
    - grep "Кузов" car_details.txt
    - grep "Двигун" car_details.txt
    - grep "Колеса" car_details.txt
    - grep "Сидіння" car_details.txt
    - grep "Кермо" car_details.txt
  dependencies:
    - build