name: Car Assembly Line

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir build

    - name: Go to build directory and create a text file
      run: |
        cd build
        touch car.txt

    - name: Add car parts to the text file
      run: |
        echo "Body" >> build/car.txt
        echo "Engine" >> build/car.txt
        echo "Wheels" >> build/car.txt

    - name: Define artifacts path
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build

    - name: Go to build directory
      run: cd build

    - name: Check for car parts in the text file
      run: |
        grep "Body" build/car.txt
        grep "Engine" build/car.txt
        grep "Wheels" build/car.txt
