name: Car Build Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        mkdir build
        cd build
        echo "Body" > car.txt
        echo "Engine" >> car.txt
        echo "Wheels" >> car.txt
        cd ..

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ubuntu:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Test
      run: |
        cd build
        grep -q "Body" car.txt && echo "Body exists" || echo "Body missing"
        grep -q "Engine" car.txt && echo "Engine exists" || echo "Engine missing"
        grep -q "Wheels" car.txt && echo "Wheels exists" || echo "Wheels missing"
